engines:
  checkstyle:
    enabled: true
  git.legal:
    enabled: true
  eslint:
    enabled: true
  fixme:
    enabled: true
  csslint:
    enabled: true
  markdownlint:
    enabled: true
  nodesecurity:
    enabled: true
  stylelint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript:
ratings:
  paths:
  - app/**
  - lib/**
  - "**.js"
